# Site settings
title: Awkward.
tag_text: Awkward.
description: Essays that matter, for people who give a damn.
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

exclude: ["README.md", "_site/"]
